// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: foot_player_detail.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//赛事对阵详情
type FootPlayerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`  //请求语言
	SportId  string `protobuf:"bytes,1,opt,name=sportId,proto3" json:"sportId,omitempty"`    //1足球 2篮球
	PersonId int64  `protobuf:"varint,2,opt,name=personId,proto3" json:"personId,omitempty"` //球队id
}

func (x *FootPlayerInfoRequest) Reset() {
	*x = FootPlayerInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foot_player_detail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FootPlayerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FootPlayerInfoRequest) ProtoMessage() {}

func (x *FootPlayerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foot_player_detail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FootPlayerInfoRequest.ProtoReflect.Descriptor instead.
func (*FootPlayerInfoRequest) Descriptor() ([]byte, []int) {
	return file_foot_player_detail_proto_rawDescGZIP(), []int{0}
}

func (x *FootPlayerInfoRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *FootPlayerInfoRequest) GetSportId() string {
	if x != nil {
		return x.SportId
	}
	return ""
}

func (x *FootPlayerInfoRequest) GetPersonId() int64 {
	if x != nil {
		return x.PersonId
	}
	return 0
}

type FootPlayerInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId       int64  `protobuf:"varint,3,opt,name=TeamId,proto3" json:"TeamId,omitempty"`             //球队id
	PersonId     int64  `protobuf:"varint,4,opt,name=PersonId,proto3" json:"PersonId,omitempty"`         //球员id
	PersonName   string `protobuf:"bytes,5,opt,name=PersonName,proto3" json:"PersonName,omitempty"`      //球员中文名
	EnglishName  string `protobuf:"bytes,6,opt,name=EnglishName,proto3" json:"EnglishName,omitempty"`    //球员英文名
	Contry       string `protobuf:"bytes,7,opt,name=Contry,proto3" json:"Contry,omitempty"`              //球员国家
	Age          int64  `protobuf:"varint,8,opt,name=Age,proto3" json:"Age,omitempty"`                   //球员年龄
	BrithDay     string `protobuf:"bytes,9,opt,name=BrithDay,proto3" json:"BrithDay,omitempty"`          //出生年月日
	TeamName     string `protobuf:"bytes,10,opt,name=TeamName,proto3" json:"TeamName,omitempty"`         //球队名称
	Position     string `protobuf:"bytes,11,opt,name=Position,proto3" json:"Position,omitempty"`         //位置【前锋、后卫...】
	ClothesNum   int64  `protobuf:"varint,12,opt,name=ClothesNum,proto3" json:"ClothesNum,omitempty"`    //衣服号码
	Height       string `protobuf:"bytes,13,opt,name=Height,proto3" json:"Height,omitempty"`             //身高
	Weight       string `protobuf:"bytes,14,opt,name=Weight,proto3" json:"Weight,omitempty"`             //体重
	Image        string `protobuf:"bytes,15,opt,name=Image,proto3" json:"Image,omitempty"`               //头像
	Honor        string `protobuf:"bytes,16,opt,name=Honor,proto3" json:"Honor,omitempty"`               //简介
	TeamImages   string `protobuf:"bytes,17,opt,name=TeamImages,proto3" json:"TeamImages,omitempty"`     //球队队徽
	NationalFlag string `protobuf:"bytes,18,opt,name=NationalFlag,proto3" json:"NationalFlag,omitempty"` //国旗
	Value        string `protobuf:"bytes,19,opt,name=Value,proto3" json:"Value,omitempty"`               //身价
	Contract     int64  `protobuf:"varint,20,opt,name=Contract,proto3" json:"Contract,omitempty"`        //合同到期时间
}

func (x *FootPlayerInfoResponse) Reset() {
	*x = FootPlayerInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foot_player_detail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FootPlayerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FootPlayerInfoResponse) ProtoMessage() {}

func (x *FootPlayerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foot_player_detail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FootPlayerInfoResponse.ProtoReflect.Descriptor instead.
func (*FootPlayerInfoResponse) Descriptor() ([]byte, []int) {
	return file_foot_player_detail_proto_rawDescGZIP(), []int{1}
}

func (x *FootPlayerInfoResponse) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *FootPlayerInfoResponse) GetPersonId() int64 {
	if x != nil {
		return x.PersonId
	}
	return 0
}

func (x *FootPlayerInfoResponse) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetEnglishName() string {
	if x != nil {
		return x.EnglishName
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetContry() string {
	if x != nil {
		return x.Contry
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *FootPlayerInfoResponse) GetBrithDay() string {
	if x != nil {
		return x.BrithDay
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetClothesNum() int64 {
	if x != nil {
		return x.ClothesNum
	}
	return 0
}

func (x *FootPlayerInfoResponse) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetHonor() string {
	if x != nil {
		return x.Honor
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetTeamImages() string {
	if x != nil {
		return x.TeamImages
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetNationalFlag() string {
	if x != nil {
		return x.NationalFlag
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FootPlayerInfoResponse) GetContract() int64 {
	if x != nil {
		return x.Contract
	}
	return 0
}

var File_foot_player_detail_proto protoreflect.FileDescriptor

var file_foot_player_detail_proto_rawDesc = []byte{
	0x0a, 0x18, 0x66, 0x6f, 0x6f, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x15, 0x46, 0x6f,
	0x6f, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xfe, 0x03, 0x0a, 0x16, 0x46, 0x6f, 0x6f, 0x74, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x67, 0x6c, 0x69, 0x73, 0x68, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x45, 0x6e, 0x67, 0x6c, 0x69,
	0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x79,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x41, 0x67, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x42, 0x72, 0x69, 0x74, 0x68, 0x44, 0x61, 0x79, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x42, 0x72, 0x69, 0x74, 0x68, 0x44, 0x61, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x54, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x54, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65, 0x73, 0x4e,
	0x75, 0x6d, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x6c, 0x6f, 0x74, 0x68, 0x65,
	0x73, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x57, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x48, 0x6f,
	0x6e, 0x6f, 0x72, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x48, 0x6f, 0x6e, 0x6f, 0x72,
	0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x11,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x6c, 0x61, 0x67,
	0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x46, 0x6c, 0x61, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x13, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foot_player_detail_proto_rawDescOnce sync.Once
	file_foot_player_detail_proto_rawDescData = file_foot_player_detail_proto_rawDesc
)

func file_foot_player_detail_proto_rawDescGZIP() []byte {
	file_foot_player_detail_proto_rawDescOnce.Do(func() {
		file_foot_player_detail_proto_rawDescData = protoimpl.X.CompressGZIP(file_foot_player_detail_proto_rawDescData)
	})
	return file_foot_player_detail_proto_rawDescData
}

var file_foot_player_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_foot_player_detail_proto_goTypes = []interface{}{
	(*FootPlayerInfoRequest)(nil),  // 0: FootPlayerInfoRequest
	(*FootPlayerInfoResponse)(nil), // 1: FootPlayerInfoResponse
}
var file_foot_player_detail_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foot_player_detail_proto_init() }
func file_foot_player_detail_proto_init() {
	if File_foot_player_detail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_foot_player_detail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FootPlayerInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foot_player_detail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FootPlayerInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foot_player_detail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foot_player_detail_proto_goTypes,
		DependencyIndexes: file_foot_player_detail_proto_depIdxs,
		MessageInfos:      file_foot_player_detail_proto_msgTypes,
	}.Build()
	File_foot_player_detail_proto = out.File
	file_foot_player_detail_proto_rawDesc = nil
	file_foot_player_detail_proto_goTypes = nil
	file_foot_player_detail_proto_depIdxs = nil
}
