// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: IncrId2SupId.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//指数-列表
type IncrId2SupIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`      //  自增 id
	Types string `protobuf:"bytes,4,opt,name=types,proto3" json:"types,omitempty"` //类型
}

func (x *IncrId2SupIdRequest) Reset() {
	*x = IncrId2SupIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IncrId2SupId_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrId2SupIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrId2SupIdRequest) ProtoMessage() {}

func (x *IncrId2SupIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_IncrId2SupId_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrId2SupIdRequest.ProtoReflect.Descriptor instead.
func (*IncrId2SupIdRequest) Descriptor() ([]byte, []int) {
	return file_IncrId2SupId_proto_rawDescGZIP(), []int{0}
}

func (x *IncrId2SupIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IncrId2SupIdRequest) GetTypes() string {
	if x != nil {
		return x.Types
	}
	return ""
}

type IncrId2SupIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupplyId int64  `protobuf:"varint,1,opt,name=supplyId,proto3" json:"supplyId,omitempty"` //
	Types    string `protobuf:"bytes,2,opt,name=types,proto3" json:"types,omitempty"`        //类型
}

func (x *IncrId2SupIdResponse) Reset() {
	*x = IncrId2SupIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_IncrId2SupId_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrId2SupIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrId2SupIdResponse) ProtoMessage() {}

func (x *IncrId2SupIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_IncrId2SupId_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrId2SupIdResponse.ProtoReflect.Descriptor instead.
func (*IncrId2SupIdResponse) Descriptor() ([]byte, []int) {
	return file_IncrId2SupId_proto_rawDescGZIP(), []int{1}
}

func (x *IncrId2SupIdResponse) GetSupplyId() int64 {
	if x != nil {
		return x.SupplyId
	}
	return 0
}

func (x *IncrId2SupIdResponse) GetTypes() string {
	if x != nil {
		return x.Types
	}
	return ""
}

var File_IncrId2SupId_proto protoreflect.FileDescriptor

var file_IncrId2SupId_proto_rawDesc = []byte{
	0x0a, 0x12, 0x49, 0x6e, 0x63, 0x72, 0x49, 0x64, 0x32, 0x53, 0x75, 0x70, 0x49, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x13, 0x49, 0x6e, 0x63, 0x72, 0x49, 0x64, 0x32, 0x53,
	0x75, 0x70, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x22, 0x48, 0x0a, 0x14, 0x49, 0x6e, 0x63, 0x72, 0x49, 0x64, 0x32, 0x53, 0x75, 0x70, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x70,
	0x70, 0x6c, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x75, 0x70,
	0x70, 0x6c, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_IncrId2SupId_proto_rawDescOnce sync.Once
	file_IncrId2SupId_proto_rawDescData = file_IncrId2SupId_proto_rawDesc
)

func file_IncrId2SupId_proto_rawDescGZIP() []byte {
	file_IncrId2SupId_proto_rawDescOnce.Do(func() {
		file_IncrId2SupId_proto_rawDescData = protoimpl.X.CompressGZIP(file_IncrId2SupId_proto_rawDescData)
	})
	return file_IncrId2SupId_proto_rawDescData
}

var file_IncrId2SupId_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_IncrId2SupId_proto_goTypes = []interface{}{
	(*IncrId2SupIdRequest)(nil),  // 0: IncrId2SupIdRequest
	(*IncrId2SupIdResponse)(nil), // 1: IncrId2SupIdResponse
}
var file_IncrId2SupId_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_IncrId2SupId_proto_init() }
func file_IncrId2SupId_proto_init() {
	if File_IncrId2SupId_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_IncrId2SupId_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrId2SupIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_IncrId2SupId_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrId2SupIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_IncrId2SupId_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_IncrId2SupId_proto_goTypes,
		DependencyIndexes: file_IncrId2SupId_proto_depIdxs,
		MessageInfos:      file_IncrId2SupId_proto_msgTypes,
	}.Build()
	File_IncrId2SupId_proto = out.File
	file_IncrId2SupId_proto_rawDesc = nil
	file_IncrId2SupId_proto_goTypes = nil
	file_IncrId2SupId_proto_depIdxs = nil
}
