// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: odd_filter.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//指数-列表
type FootOddFilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FootOddFilterRequest) Reset() {
	*x = FootOddFilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odd_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FootOddFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FootOddFilterRequest) ProtoMessage() {}

func (x *FootOddFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_odd_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FootOddFilterRequest.ProtoReflect.Descriptor instead.
func (*FootOddFilterRequest) Descriptor() ([]byte, []int) {
	return file_odd_filter_proto_rawDescGZIP(), []int{0}
}

type FootOddFilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OddsList []*Odds `protobuf:"bytes,1,rep,name=oddsList,proto3" json:"oddsList,omitempty"`
}

func (x *FootOddFilterResponse) Reset() {
	*x = FootOddFilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odd_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FootOddFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FootOddFilterResponse) ProtoMessage() {}

func (x *FootOddFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_odd_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FootOddFilterResponse.ProtoReflect.Descriptor instead.
func (*FootOddFilterResponse) Descriptor() ([]byte, []int) {
	return file_odd_filter_proto_rawDescGZIP(), []int{1}
}

func (x *FootOddFilterResponse) GetOddsList() []*Odds {
	if x != nil {
		return x.OddsList
	}
	return nil
}

type Odds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string                `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	LittleTitle string                `protobuf:"bytes,2,opt,name=littleTitle,proto3" json:"littleTitle,omitempty"`
	List        []*FootOddFiilterList `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *Odds) Reset() {
	*x = Odds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odd_filter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Odds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Odds) ProtoMessage() {}

func (x *Odds) ProtoReflect() protoreflect.Message {
	mi := &file_odd_filter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Odds.ProtoReflect.Descriptor instead.
func (*Odds) Descriptor() ([]byte, []int) {
	return file_odd_filter_proto_rawDescGZIP(), []int{2}
}

func (x *Odds) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Odds) GetLittleTitle() string {
	if x != nil {
		return x.LittleTitle
	}
	return ""
}

func (x *Odds) GetList() []*FootOddFiilterList {
	if x != nil {
		return x.List
	}
	return nil
}

type FootOddFiilterList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                              //对象ID
	TournamentStageIds []int64 `protobuf:"varint,2,rep,packed,name=tournamentStageIds,proto3" json:"tournamentStageIds,omitempty"`       //包含的赛事ID集合
	TournamentName     string  `protobuf:"bytes,3,opt,name=tournament_name,json=tournamentName,proto3" json:"tournament_name,omitempty"` //联赛名称
	Count              int64   `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	ChInitials         string  `protobuf:"bytes,4,opt,name=ch_initials,json=chInitials,proto3" json:"ch_initials,omitempty"` //
}

func (x *FootOddFiilterList) Reset() {
	*x = FootOddFiilterList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odd_filter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FootOddFiilterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FootOddFiilterList) ProtoMessage() {}

func (x *FootOddFiilterList) ProtoReflect() protoreflect.Message {
	mi := &file_odd_filter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FootOddFiilterList.ProtoReflect.Descriptor instead.
func (*FootOddFiilterList) Descriptor() ([]byte, []int) {
	return file_odd_filter_proto_rawDescGZIP(), []int{3}
}

func (x *FootOddFiilterList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FootOddFiilterList) GetTournamentStageIds() []int64 {
	if x != nil {
		return x.TournamentStageIds
	}
	return nil
}

func (x *FootOddFiilterList) GetTournamentName() string {
	if x != nil {
		return x.TournamentName
	}
	return ""
}

func (x *FootOddFiilterList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FootOddFiilterList) GetChInitials() string {
	if x != nil {
		return x.ChInitials
	}
	return ""
}

var File_odd_filter_proto protoreflect.FileDescriptor

var file_odd_filter_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6f, 0x64, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x16, 0x0a, 0x14, 0x46, 0x6f, 0x6f, 0x74, 0x4f, 0x64, 0x64, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x15, 0x46, 0x6f,
	0x6f, 0x74, 0x4f, 0x64, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x08, 0x6f, 0x64, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4f, 0x64, 0x64, 0x73, 0x52, 0x08, 0x6f, 0x64,
	0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x67, 0x0a, 0x04, 0x4f, 0x64, 0x64, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x69, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x69, 0x74, 0x74, 0x6c,
	0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x46, 0x6f, 0x6f, 0x74, 0x4f, 0x64, 0x64, 0x46, 0x69,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22,
	0xb4, 0x01, 0x0a, 0x12, 0x46, 0x6f, 0x6f, 0x74, 0x4f, 0x64, 0x64, 0x46, 0x69, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x12, 0x74, 0x6f, 0x75, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x12, 0x74, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x6f, 0x75, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x74, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x68, 0x5f, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x68, 0x49, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_odd_filter_proto_rawDescOnce sync.Once
	file_odd_filter_proto_rawDescData = file_odd_filter_proto_rawDesc
)

func file_odd_filter_proto_rawDescGZIP() []byte {
	file_odd_filter_proto_rawDescOnce.Do(func() {
		file_odd_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_odd_filter_proto_rawDescData)
	})
	return file_odd_filter_proto_rawDescData
}

var file_odd_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_odd_filter_proto_goTypes = []interface{}{
	(*FootOddFilterRequest)(nil),  // 0: FootOddFilterRequest
	(*FootOddFilterResponse)(nil), // 1: FootOddFilterResponse
	(*Odds)(nil),                  // 2: Odds
	(*FootOddFiilterList)(nil),    // 3: FootOddFiilterList
}
var file_odd_filter_proto_depIdxs = []int32{
	2, // 0: FootOddFilterResponse.oddsList:type_name -> Odds
	3, // 1: Odds.list:type_name -> FootOddFiilterList
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_odd_filter_proto_init() }
func file_odd_filter_proto_init() {
	if File_odd_filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_odd_filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FootOddFilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odd_filter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FootOddFilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odd_filter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Odds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odd_filter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FootOddFiilterList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odd_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_odd_filter_proto_goTypes,
		DependencyIndexes: file_odd_filter_proto_depIdxs,
		MessageInfos:      file_odd_filter_proto_msgTypes,
	}.Build()
	File_odd_filter_proto = out.File
	file_odd_filter_proto_rawDesc = nil
	file_odd_filter_proto_goTypes = nil
	file_odd_filter_proto_depIdxs = nil
}
