// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: sqlite_db_time.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SqliteDbTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ground  string `protobuf:"bytes,1,opt,name=ground,proto3" json:"ground,omitempty"`    //team,tournament
	SportId int64  `protobuf:"varint,2,opt,name=sportId,proto3" json:"sportId,omitempty"` //运动类型 1足球，2篮球
	Date    string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`        //日期 “2002-01-02”
}

func (x *SqliteDbTimeRequest) Reset() {
	*x = SqliteDbTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sqlite_db_time_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SqliteDbTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqliteDbTimeRequest) ProtoMessage() {}

func (x *SqliteDbTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sqlite_db_time_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqliteDbTimeRequest.ProtoReflect.Descriptor instead.
func (*SqliteDbTimeRequest) Descriptor() ([]byte, []int) {
	return file_sqlite_db_time_proto_rawDescGZIP(), []int{0}
}

func (x *SqliteDbTimeRequest) GetGround() string {
	if x != nil {
		return x.Ground
	}
	return ""
}

func (x *SqliteDbTimeRequest) GetSportId() int64 {
	if x != nil {
		return x.SportId
	}
	return 0
}

func (x *SqliteDbTimeRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type SqliteDbTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileTime    string `protobuf:"bytes,1,opt,name=fileTime,proto3" json:"fileTime,omitempty"`       //时间戳
	Environment string `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"` //环境 dev(rel)
	FilePath    string `protobuf:"bytes,3,opt,name=filePath,proto3" json:"filePath,omitempty"`       //文件路径
}

func (x *SqliteDbTimeResponse) Reset() {
	*x = SqliteDbTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sqlite_db_time_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SqliteDbTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqliteDbTimeResponse) ProtoMessage() {}

func (x *SqliteDbTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sqlite_db_time_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqliteDbTimeResponse.ProtoReflect.Descriptor instead.
func (*SqliteDbTimeResponse) Descriptor() ([]byte, []int) {
	return file_sqlite_db_time_proto_rawDescGZIP(), []int{1}
}

func (x *SqliteDbTimeResponse) GetFileTime() string {
	if x != nil {
		return x.FileTime
	}
	return ""
}

func (x *SqliteDbTimeResponse) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *SqliteDbTimeResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

var File_sqlite_db_time_proto protoreflect.FileDescriptor

var file_sqlite_db_time_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x5f, 0x64, 0x62, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x13, 0x53, 0x71, 0x6c, 0x69, 0x74, 0x65,
	0x44, 0x62, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x22, 0x70, 0x0a, 0x14, 0x53, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x44, 0x62, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72,
	0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e,
	0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sqlite_db_time_proto_rawDescOnce sync.Once
	file_sqlite_db_time_proto_rawDescData = file_sqlite_db_time_proto_rawDesc
)

func file_sqlite_db_time_proto_rawDescGZIP() []byte {
	file_sqlite_db_time_proto_rawDescOnce.Do(func() {
		file_sqlite_db_time_proto_rawDescData = protoimpl.X.CompressGZIP(file_sqlite_db_time_proto_rawDescData)
	})
	return file_sqlite_db_time_proto_rawDescData
}

var file_sqlite_db_time_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sqlite_db_time_proto_goTypes = []interface{}{
	(*SqliteDbTimeRequest)(nil),  // 0: SqliteDbTimeRequest
	(*SqliteDbTimeResponse)(nil), // 1: SqliteDbTimeResponse
}
var file_sqlite_db_time_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sqlite_db_time_proto_init() }
func file_sqlite_db_time_proto_init() {
	if File_sqlite_db_time_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sqlite_db_time_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SqliteDbTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sqlite_db_time_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SqliteDbTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sqlite_db_time_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sqlite_db_time_proto_goTypes,
		DependencyIndexes: file_sqlite_db_time_proto_depIdxs,
		MessageInfos:      file_sqlite_db_time_proto_msgTypes,
	}.Build()
	File_sqlite_db_time_proto = out.File
	file_sqlite_db_time_proto_rawDesc = nil
	file_sqlite_db_time_proto_goTypes = nil
	file_sqlite_db_time_proto_depIdxs = nil
}
