// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: web_foot_continent_league.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//大洲下的赛事数据
type WebFootContinentLeagueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"` //请求语言
}

func (x *WebFootContinentLeagueRequest) Reset() {
	*x = WebFootContinentLeagueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_foot_continent_league_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebFootContinentLeagueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebFootContinentLeagueRequest) ProtoMessage() {}

func (x *WebFootContinentLeagueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_foot_continent_league_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebFootContinentLeagueRequest.ProtoReflect.Descriptor instead.
func (*WebFootContinentLeagueRequest) Descriptor() ([]byte, []int) {
	return file_web_foot_continent_league_proto_rawDescGZIP(), []int{0}
}

func (x *WebFootContinentLeagueRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type WebFootContinentLeagueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PopularData []*WebFootEventList           `protobuf:"bytes,1,rep,name=PopularData,proto3" json:"PopularData,omitempty"` //热门赛事列表
	List        []*WebFootContinentTournament `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`               //大洲下的赛事列表
}

func (x *WebFootContinentLeagueResponse) Reset() {
	*x = WebFootContinentLeagueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_foot_continent_league_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebFootContinentLeagueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebFootContinentLeagueResponse) ProtoMessage() {}

func (x *WebFootContinentLeagueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_foot_continent_league_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebFootContinentLeagueResponse.ProtoReflect.Descriptor instead.
func (*WebFootContinentLeagueResponse) Descriptor() ([]byte, []int) {
	return file_web_foot_continent_league_proto_rawDescGZIP(), []int{1}
}

func (x *WebFootContinentLeagueResponse) GetPopularData() []*WebFootEventList {
	if x != nil {
		return x.PopularData
	}
	return nil
}

func (x *WebFootContinentLeagueResponse) GetList() []*WebFootContinentTournament {
	if x != nil {
		return x.List
	}
	return nil
}

type WebFootContinentTournament struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64                 `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty"`                      //联赛ID
	ContinentName string                `protobuf:"bytes,4,opt,name=ContinentName,proto3" json:"ContinentName,omitempty"` //联赛名称
	Sort          int64                 `protobuf:"varint,6,opt,name=Sort,proto3" json:"Sort,omitempty"`                  //排序(忽略掉，返回数据就是已经排好了的)
	CountryList   []*WebFootCountryList `protobuf:"bytes,7,rep,name=CountryList,proto3" json:"CountryList,omitempty"`     //国家列表
}

func (x *WebFootContinentTournament) Reset() {
	*x = WebFootContinentTournament{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_foot_continent_league_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebFootContinentTournament) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebFootContinentTournament) ProtoMessage() {}

func (x *WebFootContinentTournament) ProtoReflect() protoreflect.Message {
	mi := &file_web_foot_continent_league_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebFootContinentTournament.ProtoReflect.Descriptor instead.
func (*WebFootContinentTournament) Descriptor() ([]byte, []int) {
	return file_web_foot_continent_league_proto_rawDescGZIP(), []int{2}
}

func (x *WebFootContinentTournament) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WebFootContinentTournament) GetContinentName() string {
	if x != nil {
		return x.ContinentName
	}
	return ""
}

func (x *WebFootContinentTournament) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *WebFootContinentTournament) GetCountryList() []*WebFootCountryList {
	if x != nil {
		return x.CountryList
	}
	return nil
}

type WebFootCountryList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryName string              `protobuf:"bytes,8,opt,name=CountryName,proto3" json:"CountryName,omitempty"` //国家名称
	Count       int64               `protobuf:"varint,9,opt,name=Count,proto3" json:"Count,omitempty"`            //赛事数量
	Id          int64               `protobuf:"varint,10,opt,name=Id,proto3" json:"Id,omitempty"`                 //国家ID
	PId         int64               `protobuf:"varint,11,opt,name=PId,proto3" json:"PId,omitempty"`               //国家所属大洲ID
	EventList   []*WebFootEventList `protobuf:"bytes,13,rep,name=EventList,proto3" json:"EventList,omitempty"`    //国家下的赛事数据
}

func (x *WebFootCountryList) Reset() {
	*x = WebFootCountryList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_foot_continent_league_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebFootCountryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebFootCountryList) ProtoMessage() {}

func (x *WebFootCountryList) ProtoReflect() protoreflect.Message {
	mi := &file_web_foot_continent_league_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebFootCountryList.ProtoReflect.Descriptor instead.
func (*WebFootCountryList) Descriptor() ([]byte, []int) {
	return file_web_foot_continent_league_proto_rawDescGZIP(), []int{3}
}

func (x *WebFootCountryList) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

func (x *WebFootCountryList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *WebFootCountryList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WebFootCountryList) GetPId() int64 {
	if x != nil {
		return x.PId
	}
	return 0
}

func (x *WebFootCountryList) GetEventList() []*WebFootEventList {
	if x != nil {
		return x.EventList
	}
	return nil
}

type WebFootEventList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TournamentName string `protobuf:"bytes,14,opt,name=TournamentName,proto3" json:"TournamentName,omitempty"` //联赛名称
	TournamentId   int64  `protobuf:"varint,15,opt,name=TournamentId,proto3" json:"TournamentId,omitempty"`    //联赛ID
	IsKind         int64  `protobuf:"varint,25,opt,name=IsKind,proto3" json:"IsKind,omitempty"`                //1:联赛，2：杯赛
}

func (x *WebFootEventList) Reset() {
	*x = WebFootEventList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_foot_continent_league_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebFootEventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebFootEventList) ProtoMessage() {}

func (x *WebFootEventList) ProtoReflect() protoreflect.Message {
	mi := &file_web_foot_continent_league_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebFootEventList.ProtoReflect.Descriptor instead.
func (*WebFootEventList) Descriptor() ([]byte, []int) {
	return file_web_foot_continent_league_proto_rawDescGZIP(), []int{4}
}

func (x *WebFootEventList) GetTournamentName() string {
	if x != nil {
		return x.TournamentName
	}
	return ""
}

func (x *WebFootEventList) GetTournamentId() int64 {
	if x != nil {
		return x.TournamentId
	}
	return 0
}

func (x *WebFootEventList) GetIsKind() int64 {
	if x != nil {
		return x.IsKind
	}
	return 0
}

var File_web_foot_continent_league_proto protoreflect.FileDescriptor

var file_web_foot_continent_league_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x77, 0x65, 0x62, 0x5f, 0x66, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x69,
	0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3b, 0x0a, 0x1d, 0x57, 0x65, 0x62, 0x46, 0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x69, 0x6e, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0x86,
	0x01, 0x0a, 0x1e, 0x57, 0x65, 0x62, 0x46, 0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e,
	0x65, 0x6e, 0x74, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x0b, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x57, 0x65, 0x62, 0x46, 0x6f, 0x6f, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0b, 0x50, 0x6f, 0x70, 0x75, 0x6c,
	0x61, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x57, 0x65, 0x62, 0x46, 0x6f, 0x6f, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x9d, 0x01, 0x0a, 0x1a, 0x57, 0x65, 0x62, 0x46,
	0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x75, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43,
	0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x53, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x6f, 0x72, 0x74,
	0x12, 0x35, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x57, 0x65, 0x62, 0x46, 0x6f, 0x6f, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x9f, 0x01, 0x0a, 0x12, 0x57, 0x65, 0x62, 0x46,
	0x6f, 0x6f, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x49, 0x64, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x50, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x57, 0x65,
	0x62, 0x46, 0x6f, 0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x09,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x76, 0x0a, 0x10, 0x57, 0x65, 0x62,
	0x46, 0x6f, 0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x0e, 0x54, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x54, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x54, 0x6f, 0x75,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x4b,
	0x69, 0x6e, 0x64, 0x18, 0x19, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x49, 0x73, 0x4b, 0x69, 0x6e,
	0x64, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_web_foot_continent_league_proto_rawDescOnce sync.Once
	file_web_foot_continent_league_proto_rawDescData = file_web_foot_continent_league_proto_rawDesc
)

func file_web_foot_continent_league_proto_rawDescGZIP() []byte {
	file_web_foot_continent_league_proto_rawDescOnce.Do(func() {
		file_web_foot_continent_league_proto_rawDescData = protoimpl.X.CompressGZIP(file_web_foot_continent_league_proto_rawDescData)
	})
	return file_web_foot_continent_league_proto_rawDescData
}

var file_web_foot_continent_league_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_web_foot_continent_league_proto_goTypes = []interface{}{
	(*WebFootContinentLeagueRequest)(nil),  // 0: WebFootContinentLeagueRequest
	(*WebFootContinentLeagueResponse)(nil), // 1: WebFootContinentLeagueResponse
	(*WebFootContinentTournament)(nil),     // 2: WebFootContinentTournament
	(*WebFootCountryList)(nil),             // 3: WebFootCountryList
	(*WebFootEventList)(nil),               // 4: WebFootEventList
}
var file_web_foot_continent_league_proto_depIdxs = []int32{
	4, // 0: WebFootContinentLeagueResponse.PopularData:type_name -> WebFootEventList
	2, // 1: WebFootContinentLeagueResponse.list:type_name -> WebFootContinentTournament
	3, // 2: WebFootContinentTournament.CountryList:type_name -> WebFootCountryList
	4, // 3: WebFootCountryList.EventList:type_name -> WebFootEventList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_web_foot_continent_league_proto_init() }
func file_web_foot_continent_league_proto_init() {
	if File_web_foot_continent_league_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_web_foot_continent_league_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebFootContinentLeagueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_foot_continent_league_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebFootContinentLeagueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_foot_continent_league_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebFootContinentTournament); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_foot_continent_league_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebFootCountryList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_foot_continent_league_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebFootEventList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_web_foot_continent_league_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_foot_continent_league_proto_goTypes,
		DependencyIndexes: file_web_foot_continent_league_proto_depIdxs,
		MessageInfos:      file_web_foot_continent_league_proto_msgTypes,
	}.Build()
	File_web_foot_continent_league_proto = out.File
	file_web_foot_continent_league_proto_rawDesc = nil
	file_web_foot_continent_league_proto_goTypes = nil
	file_web_foot_continent_league_proto_depIdxs = nil
}
