// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: team_stand.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//request 球队榜
type TeamStandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`  //请求语言  1:zh  2:en
	SeasonId int64  `protobuf:"varint,6,opt,name=SeasonId,proto3" json:"SeasonId,omitempty"` //年份对应id
	Mark     string `protobuf:"bytes,5,opt,name=Mark,proto3" json:"Mark,omitempty"`          //标记（ goals/points:进球 ）
	Page     int64  `protobuf:"varint,7,opt,name=Page,proto3" json:"Page,omitempty"`         //页码
	PageSize int64  `protobuf:"varint,8,opt,name=PageSize,proto3" json:"PageSize,omitempty"` //个数
}

func (x *TeamStandRequest) Reset() {
	*x = TeamStandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_team_stand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamStandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamStandRequest) ProtoMessage() {}

func (x *TeamStandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_stand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamStandRequest.ProtoReflect.Descriptor instead.
func (*TeamStandRequest) Descriptor() ([]byte, []int) {
	return file_team_stand_proto_rawDescGZIP(), []int{0}
}

func (x *TeamStandRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TeamStandRequest) GetSeasonId() int64 {
	if x != nil {
		return x.SeasonId
	}
	return 0
}

func (x *TeamStandRequest) GetMark() string {
	if x != nil {
		return x.Mark
	}
	return ""
}

func (x *TeamStandRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TeamStandRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type TeamStandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64            `protobuf:"varint,5,opt,name=Count,proto3" json:"Count,omitempty"` //总数
	List  []*TeamStandList `protobuf:"bytes,6,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *TeamStandResponse) Reset() {
	*x = TeamStandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_team_stand_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamStandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamStandResponse) ProtoMessage() {}

func (x *TeamStandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_stand_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamStandResponse.ProtoReflect.Descriptor instead.
func (*TeamStandResponse) Descriptor() ([]byte, []int) {
	return file_team_stand_proto_rawDescGZIP(), []int{1}
}

func (x *TeamStandResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TeamStandResponse) GetList() []*TeamStandList {
	if x != nil {
		return x.List
	}
	return nil
}

type TeamStandList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty"`                      //id
	TeamName      string `protobuf:"bytes,4,opt,name=TeamName,proto3" json:"TeamName,omitempty"`           //  //队伍名称
	EnName        string `protobuf:"bytes,1,opt,name=EnName,proto3" json:"EnName,omitempty"`               //  //队伍名称
	TeamImageLeyu string `protobuf:"bytes,6,opt,name=TeamImageLeyu,proto3" json:"TeamImageLeyu,omitempty"` //队伍头像
	Val           int64  `protobuf:"varint,7,opt,name=Val,proto3" json:"Val,omitempty"`                    //总数
}

func (x *TeamStandList) Reset() {
	*x = TeamStandList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_team_stand_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamStandList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamStandList) ProtoMessage() {}

func (x *TeamStandList) ProtoReflect() protoreflect.Message {
	mi := &file_team_stand_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamStandList.ProtoReflect.Descriptor instead.
func (*TeamStandList) Descriptor() ([]byte, []int) {
	return file_team_stand_proto_rawDescGZIP(), []int{2}
}

func (x *TeamStandList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TeamStandList) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *TeamStandList) GetEnName() string {
	if x != nil {
		return x.EnName
	}
	return ""
}

func (x *TeamStandList) GetTeamImageLeyu() string {
	if x != nil {
		return x.TeamImageLeyu
	}
	return ""
}

func (x *TeamStandList) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

var File_team_stand_proto protoreflect.FileDescriptor

var file_team_stand_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x10, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x4d, 0x61, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d,
	0x61, 0x72, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x4d, 0x0a, 0x11, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54,
	0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x6e, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x45, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x45, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x65, 0x61, 0x6d,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x65, 0x79, 0x75, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4c, 0x65, 0x79, 0x75, 0x12, 0x10,
	0x0a, 0x03, 0x56, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x56, 0x61, 0x6c,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_team_stand_proto_rawDescOnce sync.Once
	file_team_stand_proto_rawDescData = file_team_stand_proto_rawDesc
)

func file_team_stand_proto_rawDescGZIP() []byte {
	file_team_stand_proto_rawDescOnce.Do(func() {
		file_team_stand_proto_rawDescData = protoimpl.X.CompressGZIP(file_team_stand_proto_rawDescData)
	})
	return file_team_stand_proto_rawDescData
}

var file_team_stand_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_team_stand_proto_goTypes = []interface{}{
	(*TeamStandRequest)(nil),  // 0: TeamStandRequest
	(*TeamStandResponse)(nil), // 1: TeamStandResponse
	(*TeamStandList)(nil),     // 2: TeamStandList
}
var file_team_stand_proto_depIdxs = []int32{
	2, // 0: TeamStandResponse.list:type_name -> TeamStandList
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_team_stand_proto_init() }
func file_team_stand_proto_init() {
	if File_team_stand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_team_stand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamStandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_team_stand_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamStandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_team_stand_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamStandList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_team_stand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_team_stand_proto_goTypes,
		DependencyIndexes: file_team_stand_proto_depIdxs,
		MessageInfos:      file_team_stand_proto_msgTypes,
	}.Build()
	File_team_stand_proto = out.File
	file_team_stand_proto_rawDesc = nil
	file_team_stand_proto_goTypes = nil
	file_team_stand_proto_depIdxs = nil
}
